/* Automatically generated by hbmk2. Do not edit. */
#define _HBMK_BUILD_ID_            "2"
#define _HBMK_BUILD_ID_NUM_        2
#define _HBMK_BUILD_YEAR_          "2018"
#define _HBMK_BUILD_DATE_          "20180706"
#define _HBMK_BUILD_TIME_          "16:46:36"
#define _HBMK_BUILD_TIMESTAMP_     "20180706164636673"
#define _HBMK_BUILD_TIMESTAMP_UTC_ "20180706194636673"
#define _HBMK_BUILD_RANDSTR_32_    "3d22805167509c9ddabbb33e7e222ece99b321b8cc19f6a886484e0cfe014579"
